name: reverse-proxy-local

version: "3.9"

services:
    traefik:
        image: traefik:v3.0
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.network=reverse-proxy"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
            - "--log.level=debug"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        ports:
            - "80:80"
            - "8080:8080"
        networks:
            - reverse-proxy

networks:
    reverse-proxy:
        driver: bridge
        external: true
